---
kdevops_ansible_cfg_deprecation_warnings: True
kdevops_ansible_cfg_callback_plugin_string: dense
kdevops_ansible_cfg_callback_plugin_check_mode_markers: False
kdevops_ansible_cfg_callback_plugin_display_failed_stderr: False
kdevops_ansible_cfg_callback_plugin_display_ok_hosts: True
kdevops_ansible_cfg_callback_plugin_display_skipped_hosts: True
kdevops_ansible_cfg_callback_plugin_show_custom_stats: False
kdevops_ansible_cfg_callback_plugin_show_per_host_start: True
kdevops_ansible_cfg_callback_plugin_show_task_path_on_failure: True
